"use strict";
let espectador = new Espectador();
console.log(espectador);
let espectador1 = new Espectador();
console.log(espectador1);
let espectador2 = new Espectador();
console.log(espectador2);
let espectador3 = new Espectador();
console.log(espectador3);
let espectador4 = new Espectador();
console.log(espectador4);
let espectador5 = new Espectador();
console.log(espectador5);
